version: "3.8"
services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "${NGINX_PORT}:80"

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql

  php:
    build:
      context: ./docker/development/php
    restart: always
    volumes:
      - ./project:/app
      - composer:/root/.composer/cache
    tty: true
    depends_on:
      - mysql

  nginx:
    build:
      context: ./docker/development/nginx
    restart: always
    volumes:
      - ./project:/app
    environment:
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
    depends_on:
      - php
      - proxy

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      VIRTUAL_HOST: ${ADMINER_VIRTUAL_HOST}
    depends_on:
      - proxy

volumes:
  composer:
